/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>

/* Header for class edu_asu_msrs_artcelerationlibrary_MotionBlur */

using namespace std;

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_MotionBlur
#define _Included_edu_asu_msrs_artcelerationlibrary_MotionBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_MotionBlur
 * Method:    getMotionBlur
 * Signature: ([[I[[I[[I)[[I
 */
JNIEXPORT void JNICALL Java_edu_asu_msrs_artcelerationlibrary_MotionBlur_getMotionBlur
(JNIEnv*, jclass, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
