/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
/* Header for class edu_asu_msrs_artcelerationlibrary_ColorFilter */

using namespace std;

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_ColorFilter
#define _Included_edu_asu_msrs_artcelerationlibrary_ColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_ColorFilter
 * Method:    getColorFilter
 * Signature: ([ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_edu_asu_msrs_artcelerationlibrary_ColorFilter_getColorFilter
  (JNIEnv *, jclass, jintArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
