/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>

/* Header for class edu_asu_msrs_artcelerationlibrary_GaussianBlur */

using namespace std;

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_GaussianBlur
#define _Included_edu_asu_msrs_artcelerationlibrary_GaussianBlur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_GaussianBlur
 * Method:    getGaussianBlur
 * Signature: (IFLandroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_edu_asu_msrs_artcelerationlibrary_GaussianBlur_getGaussianBlur
  (JNIEnv *, jclass, jint, jfloat, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
