/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>

/* Header for class edu_asu_msrs_artcelerationlibrary_SobelEdgeFilter */

using namespace std;

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_SobelEdgeFilter
#define _Included_edu_asu_msrs_artcelerationlibrary_SobelEdgeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_SobelEdgeFilter
 * Method:    getSobelEdgeFilter
 * Signature: (ILandroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_edu_asu_msrs_artcelerationlibrary_SobelEdgeFilter_getSobelEdgeFilter
  (JNIEnv *, jclass, jint, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
