/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>

/* Header for class edu_asu_msrs_artcelerationlibrary_UnsharpMask */

using namespace std;

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_UnsharpMask
#define _Included_edu_asu_msrs_artcelerationlibrary_UnsharpMask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_UnsharpMask
 * Method:    getUnsharpMask
 * Signature: (IFFLandroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_edu_asu_msrs_artcelerationlibrary_UnsharpMask_getUnsharpMask
  (JNIEnv *, jclass, jint, jfloat, jfloat, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
